<?php

$assets = [
    'logo' => 'assets/site/logo.png',
    'mark' => 'assets/site/renovado.png',
    'favicon' => 'assets/site/favicon.png',
    'hero' => 'assets/site/assets/entradahospitalnew.jpg',
    'doctors' => 'assets/site/assets/DSC00177-DrupFA59.jpg',
    'doctor_secondary' => 'assets/site/assets/DSC00179-Rb-eJ1cT.jpg',
    'reception' => 'assets/site/assets/DSC09402-CuAoyZOa.jpg',
    'corridor' => 'assets/site/assets/DSC09415-CLWrawks.jpg',
    'room' => 'assets/site/assets/DSC09599-C_i1oDLF.jpg',
    'bed' => 'assets/site/assets/DSC09484-BeUY45vD.jpg',
    'mamography' => 'assets/site/assets/DSC09497-DLi1Fpy-.jpg',
    'xray' => 'assets/site/assets/DSC09525-vE_gZgLx.jpg',
    'ct' => 'assets/site/assets/DSC09538-CyfojmYI.jpg',
    'exam' => 'assets/site/assets/DSC09544-CJJT60MC.jpg',
    'video' => 'assets/site/assets/videohospital-web.mp4',
];

$navItems = [
    ['id' => 'inicio', 'label' => 'Inicio'],
    ['id' => 'nosotros', 'label' => 'Nosotros'],
    ['id' => 'servicios', 'label' => 'Servicios'],
    ['id' => 'instalaciones', 'label' => 'Instalaciones'],
    ['id' => 'pacientes', 'label' => 'Pacientes'],
    ['id' => 'contacto', 'label' => 'Contacto'],
];

$quickAccess = [
    [
        'icon' => 'ambulance',
        'title' => 'Emergencias 24/7',
        'text' => 'Atención inmediata adulto y pediátrica.',
        'meta' => '(809) 806-0444',
        'tone' => 'red',
    ],
    [
        'icon' => 'calendar-days',
        'title' => 'Agendar cita',
        'text' => 'Coordina tu consulta con nuestros especialistas.',
        'meta' => 'Solicitud en línea',
        'tone' => 'green',
    ],
    [
        'icon' => 'shield-check',
        'title' => 'Aseguradoras',
        'text' => 'Atención organizada para pacientes y convenios.',
        'meta' => 'Soporte administrativo',
        'tone' => 'navy',
    ],
    [
        'icon' => 'map-pin',
        'title' => 'Ubicacion',
        'text' => 'Av. 27 de Febrero, Plaza Colinas Mall.',
        'meta' => 'Santiago, Rep. Dom.',
        'tone' => 'violet',
    ],
];

$services = [
    'consultas' => [
        'label' => 'Consulta Especializada',
        'icon' => 'stethoscope',
        'description' => 'Más de 28 especialidades orientadas a diagnóstico, seguimiento y continuidad clínica.',
        'items' => [
            'Alergología e Inmunología',
            'Anestesiología',
            'Cardiología',
            'Dermatología',
            'Endocrinología',
            'Gastroenterología',
            'Geriatría',
            'Ginecología y Obstetricia',
            'Hematología',
            'Infectología',
            'Maxilofacial',
            'Medicina Física y Rehabilitación',
            'Medicina Interna',
            'Nefrología',
            'Neonatología',
            'Neumología',
            'Neurocirugía',
            'Neurología Clínica',
            'Nutrición Clínica',
            'Oftalmología',
            'Oncología',
            'Ortopedia y Traumatología',
            'Otorrinolaringología',
            'Pediatría',
            'Psicología Clínica',
            'Psiquiatría',
            'Reumatología',
            'Urología',
        ],
    ],
    'diagnostico' => [
        'label' => 'Apoyo Diagnóstico',
        'icon' => 'microscope',
        'description' => 'Imágenes, laboratorio y pruebas especializadas para decisiones médicas oportunas.',
        'items' => [
            'Laboratorio Clínico y Banco de Sangre',
            'Resonancia Magnética',
            'Tomografía',
            'Densitometría',
            'Mamografía',
            'Radiografía y Panorámica',
            'Sonografía',
            'Doppler',
            'Anatomía Patológica',
            'Ecocardiograma',
            'Holter',
            'MAPA',
            'Prueba de Esfuerzo',
            'Unidad Endoscópica (Broncoscopía, Colonoscopía, Gastroscopía)',
        ],
    ],
    'cirugia' => [
        'label' => 'Bloque Quirúrgico',
        'icon' => 'scissors',
        'description' => 'Quirófanos modernos, recuperación y equipos para procedimientos de alta precisión.',
        'items' => [
            'Cirugía Cardiovascular',
            'Cirugía General',
            'Cirugía Ginecológica',
            'Cirugía Laparoscópica',
            'Cirugía Maxilofacial',
            'Cirugía Oftalmológica',
            'Cirugía Oncológica',
            'Cirugía Pediátrica',
            'Cirugía Torácica',
            'Cirugía Urológica',
            'Neurocirugía',
        ],
    ],
    'clinicos' => [
        'label' => 'Servicios Clínicos',
        'icon' => 'heart-pulse',
        'description' => 'Atención hospitalaria continua para pacientes ambulatorios, ingresados y críticos.',
        'items' => [
            'Emergencia Adulto y Pediátrica',
            'Hospitalización',
            'Hemodiálisis',
            'Hemodinamia',
            'Medicina del Dolor',
            'Quimioterapia',
            'Vacunación',
            'Cuidados Intensivos (Adulto, Pediátrico, Neonatal)',
        ],
    ],
];

$values = [
    'Solidaridad',
    'Respeto',
    'Empatía',
    'Calidad',
    'Compromiso',
    'Compasión',
    'Honestidad',
    'Responsabilidad',
    'Trabajo en Equipo',
    'Innovación',
    'Transparencia',
    'Inclusión',
];

$patientRights = [
    'Recibir asistencia sin discriminación.',
    'Atención médica bajo marco ético y legal.',
    'Atención adecuada y oportuna en ambiente limpio.',
    'Atención de emergencia si la necesita.',
    'Conocer nombres y cargos del personal.',
    'Trato con respeto a su dignidad humana.',
    'Privacidad e intimidad.',
    'Respeto a creencias religiosas y filosóficas.',
    'Comunicación con familiares y exterior.',
    'Información completa sobre diagnóstico y tratamiento.',
    'Manejo óptimo del dolor.',
    'Información para consentimiento informado.',
    'Rechazar tratamiento con conocimiento de efectos.',
    'Acceso a su historia clínica.',
    'Confidencialidad de su expediente.',
    'Recibir factura desglosada.',
    'Presentar quejas y reclamaciones.',
    'Morir con dignidad y soporte espiritual.',
];

$patientDuties = [
    'Proporcionar información correcta sobre su salud.',
    'Informar cambios inesperados en su condición.',
    'Hacer preguntas si no comprende el tratamiento.',
    'Seguir el plan de tratamiento recomendado.',
    'Entender consecuencias de rechazar tratamiento.',
    'Acatar reglas y reglamentos del hospital.',
    'Cumplir obligaciones financieras.',
    'Respetar derechos de otros pacientes y personal.',
    'Cuidar propiedad del hospital.',
    'Acudir a citas o avisar cancelación.',
    'Proteger sus artículos personales.',
];

$floors = [
    ['num' => '6', 'level' => '6to Nivel', 'content' => 'Áreas administrativas y Gerencia General.'],
    ['num' => '5', 'level' => '4to y 5to Nivel', 'content' => 'Internamiento: 65 habitaciones modernas y confortables.'],
    ['num' => '3', 'level' => '3er Nivel', 'content' => 'Laboratorio, imágenes y Centro de Medicina Avanzada.'],
    ['num' => '2', 'level' => '2do Nivel', 'content' => 'Bloque quirúrgico, partos, UCI y recuperación.'],
    ['num' => '1', 'level' => '1er Nivel', 'content' => 'Emergencias, farmacia, imágenes y servicios generales.'],
];

$gallery = [
    ['src' => $assets['hero'], 'title' => 'Fachada principal', 'text' => 'Acceso hospitalario conectado a Colinas Mall.'],
    ['src' => $assets['doctors'], 'title' => 'Equipo médico', 'text' => 'Especialistas con enfoque humano y resolutivo.'],
    ['src' => $assets['ct'], 'title' => 'Tomografía', 'text' => 'Imágenes diagnósticas para medicina avanzada.'],
    ['src' => $assets['mamography'], 'title' => 'Mamografía', 'text' => 'Tecnología para diagnóstico oportuno.'],
    ['src' => $assets['corridor'], 'title' => 'Circulación clínica', 'text' => 'Ambientes limpios, amplios y funcionales.'],
    ['src' => $assets['room'], 'title' => 'Internamiento', 'text' => 'Habitaciones modernas para recuperación segura.'],
    ['src' => $assets['xray'], 'title' => 'Rayos X', 'text' => 'Soporte diagnóstico integral.'],
    ['src' => $assets['exam'], 'title' => 'Consultorios', 'text' => 'Espacios equipados para atención especializada.'],
];

$contact = [
    'phone' => '(809) 806-0444',
    'email' => 'info@colinashospital.com',
    'address' => 'Av. 27 de Febrero, Plaza Colinas Mall, Santiago, Rep. Dom.',
    'instagram' => 'https://www.instagram.com/colinashospital/',
    'facebook' => 'https://www.facebook.com/profile.php?id=61583184854928',
    'maps' => 'https://www.google.com/maps/search/?api=1&query=Hospital%20General%20Las%20Colinas%20Santiago',
    'whatsapp' => 'https://wa.me/18098060444',
];
